use wad2g5t2intern;

--
-- Data for table `gender`
--
INSERT INTO
  gender(`genderID`, `genderName`)
values
  ("M", "Male"),
  ("F", "Female"),
  ("O", "Others");

--
-- Data for table `intern`
--
INSERT INTO
  intern(
    `firstName`,
    `lastName`,
    `genderID`,
    `country`,
    `school`,
    `schoolEmail`,
    `password`,
    `profilePictureUrl`,
    `reviewsNo`
  )
values
  (
    "Esther",
    "Kim",
    "F",
    "Singapore",
    "Singapore Management University",
    "esther.2020@scis.smu.edu.sg",
    "Esther@123",
    "../IMG/avatar7.svg",
    321
  ),
  (
    "Megan",
    "Thong",
    "F",
    "Singapore",
    "Singapore Management University",
    "megan.2020@scis.smu.edu.sg",
    "Megan@45",
    "../IMG/avatar3.svg",
    54
  ),
  (
    "Patricia",
    "Loi",
    "O",
    "Singapore",
    "Singapore Management University",
    "patricia.2020@scis.smu.edu.sg",
    "Patricia@67",
    "../IMG/avatar5.svg",
    76
  ),
  (
    "Tianyu",
    "Chen",
    "M",
    "Singapore",
    "Singapore Management University",
    "tianyu.2020@scis.smu.edu.sg",
    "Tianyu@90",
    "../IMG/avatar1.svg",
    9
  );
--
-- Data for table `company`
--
insert into company(
    -- `companyID`,
    `companyName`,
    `companyDescription`,
    `companyLinkedinLink`,
    `companyWebsite`,
    `industry`,
    `imageLink`,
    `location`
  )
values (
    'Google Asia Pacific, Singapore',
    'top tech giant',
    'https://sg.linkedin.com/company/google',
    'https://careers.google.com/locations/sing/',
    'Internet',
    '../IMG/google_staff.svg',
    'Alexandra Road' 
  ),
  (
    'Amazon, Singapore',
    'top tech giant',
    'https://sg.linkedin.com/company/amazon',
    'https://www.amazon.jobs/en-gb/location/singapore-singapore',
    'Internet',
    '../IMG/amazon.jpg',
    '5B Toh Guan Rd E, Singapore 608829'
  ),
  (
    'Facebook APAC HQ',
    'top tech giant',
    'https://sg.linkedin.com/company/facebook',
    'https://www.facebook.com/careers/v2/locations/singapore/?p[offices][0]=Singapore&offices[0]=Singapore',
    'Internet',
    '../IMG/facebook.jfif',
    '-'
  ),
  (
    'Microsoft',
    'top tech giant',
    'https://www.linkedin.com/company/microsoft',
    'https://careers.microsoft.com/professionals/us/en/l-singapore',
    'Technology',
    '../IMG/microsoft.jfif',
    '-'
  ),
  (
    'HP',
    'HP Inc. (NYSE: HPQ) creates technology that makes life better for everyone, everywhere. Through our product and service portfolio of personal systems, printers and 3D printing solutions, we engineer experiences that amaze.',
    'https://www.linkedin.com/company/hp',
    'https://www.hp.com/sg-en/home.html',
    'Technology',
    '../IMG/HPstaff.svg',
    '-'
  ),
  (
    'Dell',
    'Dell Inc., formerly PC’s Limited (1984–88) and Dell Computer Corporation (1988–2003), global company that designs, develops, and manufactures personal computers (PCs) and a variety of computer-related products. The company is one of the world’s leading suppliers of PCs. Dell is headquartered in Round Rock, Texas.',
    'https://www.linkedin.com/company/delltechnologies',
    'https://www.dell.com/en-sg',
    'Technology',
    '../IMG/dell.jfif',
    '-'
  ),
  (
    'Apple',
    'top tech giant',
    'https://www.linkedin.com/company/apple',
    'https://www.apple.com/careers/sg/',
    'Electronics',
    '../IMG/apple.jpg',
    '-'
  ),
  (
    'Dyson',
    'The British electric appliance firm employs approximately 1,200 people in Singapore, of whom 350 are engineers and scientists.',
    'https://sg.linkedin.com/company/dyson',
    'https://www.dyson.com.sg/',
    'Electronics',
    '../IMG/dyson.jfif',
    '-'
  ),
  (
    'DBS Bank',
    'Banking',
    'https://sg.linkedin.com/company/dbs-bank',
    'https://www.dbs.com/careers/default.page',
    'Banking',
    '../IMG/DBS.jpg',
    '-'
  ),
  (
    'UOB',
    'Banking',
    'https://sg.linkedin.com/company/uob',
    'https://www.uobgroup.com/uobgroup/index.page',
    'Banking',
    '../IMG/uob.jfif',
    '-'
  ),
  (
    'OCBC Bank',
    'Banking',
    'https://sg.linkedin.com/company/ocbc-bank',
    'https://www.ocbc.com/',
    'Banking',
    '../IMG/ocbc.jfif',
    '-'
  ),
  (
    'Standard Chartered Bank',
    'Banking',
    'https://www.linkedin.com/company/standardchartered',
    'https://www.sc.com/en/',
    'Banking',
    '../IMG/StandardCharteredBank.jpg',
    '-'
  ),
  (
    'Schneider Electric Singapore',
    'We believe access to energy and digital is a basic human right. Our generation is facing a tectonic shift in energy transition and industrial revolution catalysed by accelerated digitisation in a more electric world. Electricity is the most efficient and best vector for decarbonisation; combined with a circular economy approach, we will achieve a climate-positive impact as part of the United Nations Sustainable Development Goals.',
    'https://sg.linkedin.com/company/schneider-electric',
    'https://www.se.com/sg/en/',
    'Energy',
    '../IMG/SchneiderElectric.jfif',
    '-'
  ),
  (
    'Shell Singapore',
    'We are a global group of energy and petrochemicals companies with an average of 86,000 employees in more than 70 countries. We use advanced technologies and take an innovative approach to help build a sustainable energy future.',
    'https://www.linkedin.com/company/shell',
    'https://www.shell.com.sg/',
    'Energy',
    '../IMG/shell.jfif',
    '-'
  ),
  (
    'Food Panda',
    'Food Delivery Service',
    'https://sg.linkedin.com/company/foodpanda',
    'https://www.foodpanda.com/',
    'Others',
    '../IMG/foodpandaoffice.svg',
    '-'
  ),
  (
    'DHL',
    'Established in over 220 countries, employing over 100,000 people throughout over 3000 facilities, DHL Express serves over 2.6 million customers worldwide, making us the largest international express courier company in the world.',
    'https://www.linkedin.com/company/dhl',
    'https://dhlexpress.com.sg/',
    'Others',
    '../IMG/DHLbuilding.svg',
    '-'
  ),
  (
    'Procter & Gamble',
    'The award-winning consumer goods giant is crowned Singapore’s top employer for 2021, and with good reason. Today, Procter & Gamble Singapore is powered by over 2,000 dedicated employees from more than 40 nationalities. An ardent believer in the vast potential of cutting-edge technology, Procter & Gamble plans to invest up to $50 million in total business expenditure in Singapore to further advance digital innovation in the country. Furthermore, it has signalled its intention to train at least 50 employees to embark on novel digital roles.',
    'https://sg.linkedin.com/company/procter-and-gamble',
    'https://www.pgcareers.com/singapore',
    'Others',
    '../IMG/procterAndGamble.jfif',
    '-'
  ),
  (
    'Singapore Management University',
    'A premier university in Asia, the Singapore Management University (SMU) is internationally recognised for its world-class research and distinguished teaching. Established in 2000, SMU’s mission is to generate leading-edge research with global impact and produce broad-based, creative and entrepreneurial leaders for the knowledge-based economy.',
    'https://www.linkedin.com/school/singapore-management-university/',
    'https://www.smu.edu.sg/',
    'Others',
    '../IMG/smu.jfif',
    '-'
  ),
  (
    'Disney',
    'The mission of The Walt Disney Company is to entertain, inform and inspire people around the globe through the power of unparalleled storytelling, reflecting the iconic brands, creative minds and innovative technologies that make ours the world’s premier entertainment company.',
    'https://www.linkedin.com/company/the-walt-disney-company-southeast-asia-pte.-ltd.',
    'https://www.disney.sg/',
    'Others',
    '../IMG/disney.jfif',
    '-'
  ),
  (
    'Lazada Singapore',
    'Lazada Singapore is the leading online shopping platform in Singapore. We are always striving to keep up with what consumers want and need. We are making every effort to achieve maximum customer satisfaction through seamless transactions and competitive product pricing. We are updating and improving our product selections at the best prices to delight our customers along with great deals and flash sales.',
    'https://www.linkedin.com/company/lazada',
    'https://www.lazada.sg/',
    'Others',
    '../IMG/lazada.jfif',
    '-'
  );

--
-- Data for table `review`
--
INSERT INTO
  review(
    `companyID`,
    `reviewID`,
    `jobTitle`,
    `schoolEmail`,
    `reviewDescription`,
    `overallRating`,
    `criteria1Rating`,
    `criteria2Rating`,
    `criteria3Rating`,
    `criteria4Rating`,
    `criteria5Rating`,
    `criteria6Rating`,
    `totalUpvotesNo`,
    `totalDownvotesNo`,
    `checkSFW`
  )
values
  (
    1,
    1,
    "Web Engineer",
    "esther.2020@scis.smu.edu.sg",
    "I learnt about Search Engine Optimisation (SEO) and Google Ads, which align with my Business Analysis specialisation perfectly!",
    5,
    5,
    4,
    5,
    4,
    5,
    4,
    34,
    5,
    1
  ),
  (
    1,
    2,
    "Policy Analyst",
    "megan.2020@scis.smu.edu.sg",
    "The best internship I've had!!!",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),
  (
    2,
    3,
    "Business Analyst",
    "patricia.2020@scis.smu.edu.sg",
    "My mentor was just the nicest person ever!",
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    12,
    2,
    0
  ),
  (
    2,
    4,
    "Test Engineer",
    "esther.2020@scis.smu.edu.sg",
    "Free food at this company! :)",
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    12,
    2,
    0
  ),
  (
    3,
    5,
    "Data Scientist",
    "megan.2020@scis.smu.edu.sg",
    "The worst internship I've had.",
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0
  ),
  (
    3,
    6,
    "Data Analyst",
    "esther.2020@scis.smu.edu.sg",
    "Tooo much saikang pls avoid",
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0
  ),
  (
    4,
    7,
    "Policy Analyst",
    "patricia.2020@scis.smu.edu.sg",
    "Are you kidding me? the pple here are soooooo friendly! :)",
    5,
    5,
    5,
    5,
    3,
    5,
    5,
    1,
    2,
    0
  ),
  (
    4,
    8,
    "Policy Analyst",
    "megan.2020@scis.smu.edu.sg",
    "The mentor left me with toooo much work. Be prepared to sleep at 2am.",
    1,
    1,
    1,
    2,
    3,
    1,
    2,
    1,
    20,
    0
  ),
  (
    5,
    9,
    "Cloud Engineer",
    "esther.2020@scis.smu.edu.sg",
    "The food here is so good and cheap, I just love it. My Supervisor is super understand as well",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    4,
    2,
    0
  ),
  (
    5,
    10,
    "Front-end Developer",
    "megan.2020@scis.smu.edu.sg",
    "My supervisor is just too lovely.",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    120,
    24,
    0
  ),(
    6,
    11,
    "Policy Analyst",
    "patricia.2020@scis.smu.edu.sg",
    "Meh, nothing good to say. Did not learn much",
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    12,
    25,
    0
  ),
  (
    6,
    12,
    "HR intern",
    "esther.2020@scis.smu.edu.sg",
    "Tooo much politics, you wont like it here! Never ever come here!",
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    120000,
    0,
    0
  ),
  (
    7,
    13,
    "Policy Analyst",
    "megan.2020@scis.smu.edu.sg",
    "Love the learning experience",
    5,
    5,
    4,
    5,
    4,
    5,
    4,
    12,
    2,
    0
  ),(
    7,
    14,
    "Policy Analyst",
    "esther.2020@scis.smu.edu.sg",
    "The somewhat good internship I've had.",
    3,
    3,
    3,
    3,
    3,
    4,
    4,
    12,
    255,
    0
  ),(
    8,
    15,
    "Policy Analyst",
    "patricia.2020@scis.smu.edu.sg",
    "The boss likes to scold pple",
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    12,
    2,
    0
  ),(
    8,
    16,
    "Policy Analyst",
    "megan.2020@scis.smu.edu.sg",
    "Thankful for the learning experience",
    5,
    5,
    3,
    5,
    3,
    3,
    3,
    12,
    2,
    0
  ),(
    9,
    17,
    "Policy Analyst",
    "esther.2020@scis.smu.edu.sg",
    "Learned a lot here",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    9,
    18,
    "Logistic Assistant",
    "patricia.2020@scis.smu.edu.sg",
    "The pay is not very generous",
    1,
    5,
    4,
    5,
    4,
    4,
    4,
    120,
    0,
    0
  ),(
    10,
    19,
    "Web developer",
    "megan.2020@scis.smu.edu.sg",
    "Very generous pay",
    5,
    5,
    4,
    5,
    5,
    5,
    5,
    124,
    1,
    0
  ),(
    10,
    20,
    "UX designer",
    "patricia.2020@scis.smu.edu.sg",
    "Overall good but food is expensive here.",
    5,
    5,
    3,
    5,
    5,
    3,
    3,
    121,
    42,
    0
  ),(
    11,
    21,
    "Quality Engineer",
    "megan.2020@scis.smu.edu.sg",
    "Transport here was not easy for me. Mentors where too busy for me but I like the food there",
    4,
    3,
    3,
    3,
    3,
    3,
    3,
    132,
    2,
    0
  ),(
    11,
    22,
    "Lawyer",
    "patricia.2020@scis.smu.edu.sg",
    "Very good support here",
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    132,
    552,
    0
  ),(
    12,
    23,
    "Business Development",
    "megan.2020@scis.smu.edu.sg",
    "Great exposure for me",
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    12,
    2,
    0
  ),(
    12,
    24,
    "UX specialist",
    "patricia.2020@scis.smu.edu.sg",
    "Great mentorship",
    5,
    5,
    2,
    5,
    2,
    4.8,
    2,
    12,
    2,
    0
  ),(
    13,
    25,
    "HR executive",
    "megan.2020@scis.smu.edu.sg",
    "No body bothered to mentor me!!",
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    1882,
    2,
    0
  ),(
    13,
    26,
    "Cloud Specialist",
    "patricia.2020@scis.smu.edu.sg",
    "The worst internship I have ever had",
    2,
    2,
    2,
    2,
    2,
    4,
    2,
    1120,
    29,
    0
  ),(
    14,
    27,
    "Back end Developer",
    "esther.2020@scis.smu.edu.sg",
    "Absolutely no training provided, you have to learn everything yourself",
    3,
    3,
    3,
    3,
    3,
    1,
    5,
    1,
    22,
    0
  ),(
    14,
    28,
    "Policy Analyst",
    "tianyu.2020@scis.smu.edu.sg",
    "The best internship I've had.",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    15,
    29,
    "Policy Analyst",
    "patricia.2020@scis.smu.edu.sg",
    "The kinda okay internship I've had.",
    4,
    4,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    15,
    30,
    "Software Engineeer",
    "esther.2020@scis.smu.edu.sg",
    "Mentor is soooo patient",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    16,
    31,
    "Policy Analyst",
    "megan.2020@scis.smu.edu.sg",
    "My mentor was very kind to me",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    16,
    32,
    "Policy Analyst",
    "esther.2020@scis.smu.edu.sg",
    "Avoid the aunties here they gossip allloooot!",
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    172,
    2,
    0
  ),(
    17,
    33,
    "Policy Analyst",
    "megan.2020@scis.smu.edu.sg",
    "Free company meals",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    17,
    34,
    "Business Analyst",
    "patricia.2020@scis.smu.edu.sg",
    "It was sooooooooo fun!",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    18,
    35,
    "Policy Analyst",
    "tianyu.2020@scis.smu.edu.sg",
    "I learned so muchhh about policy :).",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    18,
    36,
    "Policy Analyst",
    "megan.2020@scis.smu.edu.sg",
    "I am very happy with my experience.",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    19,
    37,
    "Resource Coordinator",
    "esther.2020@scis.smu.edu.sg",
    "The people here are very fast-paced so watch out!",
    3,
    5,
    3,
    5,
    3,
    3,
    2,
    12,
    2,
    0
  ),(
    19,
    38,
    "Compliance Analyst",
    "tianyu.2020@scis.smu.edu.sg",
    "Wow they taught me so much!!!",
    5,
    5,
    2,
    5,
    2,
    2,
    2,
    12,
    2,
    0
  ),(
    20,
    39,
    "Human Resource Intern",
    "esther.2020@scis.smu.edu.sg",
    "People were nice but I didnt really learn much",
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    12,
    2,
    0
  ),(
    20,
    40,
    "Quality Assurance Analyst",
    "tianyu.2020@scis.smu.edu.sg",
    "The people here are very supportive and kind.",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  ),(
    20,
    NULL,
    "Quality Assurance Analyst",
    "megan.2020@scis.smu.edu.sg",
    "The people here were very nice to me in ever way!.",
    5,
    5,
    4,
    5,
    4,
    4,
    4,
    12,
    2,
    0
  );

--
-- Data for table `vote`
--
INSERT INTO
  vote(
    `companyID`,
    `reviewID`,
    `voteID`,
    `isUpvote`,
    `isDownvote`
  )
VALUES
  (1, 1, 1, 1, 0),
  (1, 1, 2, 1, 0),
  (1, 1, 3, 0, 1),
  (1, 2, 4, 1, 0),
  (1, 1, 5, 0, 1),
  (1, 2, 6, 1, 0),
  (1, 1, 7, 1, 0);